version: "3.3"

# docker run -d --rm -e WEBSWING_ADMIN_URL=http://localhost:8090 -p 8090:8090 -p 8080:8080 webswing/webswing-eval:20.2.1

services:
  webswing:
    image: webswing/webswing-eval:20.2.1
    environment:
#      - WEBSWING_CONFIG=/opt/app/config/webswing.config
#      - WEBSWING_ADMIN_URL=http://192.168.1.2:8090
#      - WEBSWING_SERVER_PUBLICURL=http://192.168.1.2
#      - WEBSWING_CONFIG=/opt/webswing/webswing.config
      - WEBSWING_ADMIN_URL=http://localhost:8090
#      - WEBSWING_SERVER_PUBLICURL=http://192.168.1.2

    volumes:
      - ./opt/app:/opt/app
    ports:
#      - "80:8080"
      - "8080:8080"
      - "8090:8090"
