version: "3.3"

services:
  webswing:
    image: webswing/webswing-eval:20.2.1
    environment:
      - WEBSWING_CONFIG=/opt/app/config/webswing.config
      - WEBSWING_SERVER_PUBLICURL=https://ristinolla.tuukkadomain.com
      - WEBSWING_ADMIN_URL=https://ristinolla.tuukkadomain.com/admin

    volumes:
      - ./opt/app:/opt/app
    ports:
      - "8080:8080"
      - "8090:8090"
